/**
 * 分类常量
 */
export default class CategoryEnum {}
CategoryEnum.SUBJECT = '1' // 科目
CategoryEnum.ATTENDANCE = '2' // 考勤
CategoryEnum.SCHOOL = '3' // 学校
CategoryEnum.REVIEW = '4' // 评价
CategoryEnum.GRADE = '5' // 年级
CategoryEnum.APPROVE = '6' // 审批
CategoryEnum.GRADE_SUBJECT = '7' // 年级下面不同学期的课程
CategoryEnum.SUBJECT_VERSION = '8' // 科目下面版本类型
CategoryEnum.VERSION_UNIT = '9' // 版本下面单元类型
CategoryEnum.UNIT_COURSE = '10' // 单元下面课程类型
CategoryEnum.CHAPTER = '11' // 章节
CategoryEnum.SCORE = '15' // 成绩的字段列
CategoryEnum.COMPLAIN_TYPE = 'complainType' // 举报类型
CategoryEnum.SICK = '17' // 病假类型
CategoryEnum.WORK_ORDER = '18' // 任务
CategoryEnum.DESIGN_TEMPLATE = '19' // 教学计划
CategoryEnum.CUSTOMER = '21' // 客户分类
CategoryEnum.RATING = '22' // 评比分类
CategoryEnum.MEDAL = '23' // 勋章纬度
CategoryEnum.MEDAL_PHOTO = '24' // 勋章墙图片
CategoryEnum.VSCREEN_MSG_TYPE = '26' // V屏消息分类
CategoryEnum.CAUSE = '27' // 疾控中心病因
CategoryEnum.KNOWLEDGE_PARENT = '28' // 知识点父分类
CategoryEnum.KNOWLEDGE_CHILD = '29' // 知识点子分类
CategoryEnum.ENROLL = '30' // 报名分类数据
CategoryEnum.DINING = '31' // 食堂
CategoryEnum.FOOD = '32' // 菜式
CategoryEnum.SCORESHOW = '33' // 成绩展示分类数据
CategoryEnum.SCORESHOW_CHILD = '34' // 成绩展示子分类
CategoryEnum.WAGE_TEMPLATE = '35' // 工资单模板
CategoryEnum.TEACHER_LEAVE = '36' // 请假类型
CategoryEnum.DUTY = '38' // 值日老师分类数据
CategoryEnum.HOMEWORK_COMMIT = '39'
CategoryEnum.PRAXIS_Q_TYPE_TITLE = '41' // 按题型（标题分栏）
CategoryEnum.PRAXIS_Q_TYPE = '42' // 题型
CategoryEnum.PRAXIS_Q_CULTY_TITLE = '43' // 按困难程度（标题分栏）
CategoryEnum.PRAXIS_Q_CULTY = '44' // 难易程度
CategoryEnum.BIRTHDAY_CARD = '45' // 生日贺卡
CategoryEnum.RESCOURSE_TYPE = '46' // 资源发布为
CategoryEnum.HONORCLASS_TYPE = '49' // 资源发布为
CategoryEnum.QUALITY = '51' // 质量分析模板
CategoryEnum.CUSTOMER_TYPE = '52' // CRM客户类型
CategoryEnum.CUSTOMER_POWER_TYPE = '53' // CRM客户把握度
CategoryEnum.CRM_PRODUCT = '54' // 产品
CategoryEnum.CRM_CHANNEL = '55' // 渠道
CategoryEnum.READ_TYPE = '56' // 阅读类型
CategoryEnum.READ_BEST_TYPE = '57' // 阅读任务 评论最热最新
CategoryEnum.READ_RANGE_TYPE = '58' // 阅读任务 书评范围
CategoryEnum.DEPLOY_PROCESS = '60' // CRM部署进展
CategoryEnum.BUSINESS_PROCESS = '61' // CRM商务进展
CategoryEnum.SHOPPING_TYPE = '63' // 商城商品类型
CategoryEnum.SCHOOLACTIVE = '66' // 商城商品类型
CategoryEnum.STAYED_GOHOME = '67' // 放学留堂
CategoryEnum.BILLTYPE = '68' // 发票类型
CategoryEnum.PRINTBILLTYPE = '69' // 开票类型
CategoryEnum.RATING = '70' // 七彩评比维度分类
CategoryEnum.ROLE = '71' // 教师评价角色
CategoryEnum.WORK_PERMISSIONSS = '72' // 作业答卷查看权限
CategoryEnum.CRM_TITLE = '73' // CRM职务
